# Generated by Django 2.1.4 on 2019-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=40)),
                ('dob', models.DateField(default=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(default=False, max_length=20)),
                ('gender', models.CharField(default=False, max_length=10)),
                ('mobile', models.IntegerField(default=False)),
                ('address', models.CharField(default=False, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='applicationform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('mob', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default=False, max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('cno', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField()),
                ('empid', models.IntegerField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='recuirtment',
            fields=[
                ('oppcode', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=30)),
                ('startregistration', models.DateField()),
                ('age', models.IntegerField()),
                ('lastregistration', models.DateField()),
                ('deptid', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('responsibilities', models.CharField(max_length=250)),
                ('cno', models.IntegerField()),
            ],
        ),
    ]
