# Generated by Django 2.1.4 on 2019-02-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalinterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.IntegerField()),
                ('interviewer', models.IntegerField()),
                ('schedule', models.CharField(max_length=30)),
                ('appid', models.IntegerField()),
                ('res', models.CharField(max_length=20)),
            ],
        ),
    ]
